// <auto-generated />
using System;
using EAD.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EAD.Migrations
{
    [DbContext(typeof(EadProjectContext))]
    [Migration("20251229075516_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EAD.Models.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("GeneratedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PaidOn")
                        .HasColumnType("datetime");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("VerifiedByAdmin")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId", "GeneratedOn" }, "UQ_User_GeneratedOn")
                        .IsUnique();

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("EAD.Models.BillRecheckRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<string>("RequestMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RequestedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__BillRech__3214EC0729003E27");

                    b.HasIndex("BillId");

                    b.HasIndex("UserId");

                    b.ToTable("BillRecheckRequests");
                });

            modelBuilder.Entity("EAD.Models.DailyConsumption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BillId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ConsumptionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.Property<bool>("IsBilled")
                        .HasColumnType("bit");

                    b.Property<int>("MealItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("WasUserPresent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id")
                        .HasName("PK__DailyCon__3214EC074D020E3D");

                    b.HasIndex("BillId");

                    b.HasIndex("MealItemId");

                    b.HasIndex(new[] { "UserId", "MealItemId", "ConsumptionDate" }, "UQ_DailyConsumption")
                        .IsUnique();

                    b.ToTable("DailyConsumptions");
                });

            modelBuilder.Entity("EAD.Models.DailyMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MealItemId")
                        .HasColumnType("int");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__DailyMen__3214EC0785AD9854");

                    b.HasIndex("MealItemId");

                    b.ToTable("DailyMenu", (string)null);
                });

            modelBuilder.Entity("EAD.Models.MealItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__tmp_ms_x__3214EC077CB09D50");

                    b.ToTable("MealItems");
                });

            modelBuilder.Entity("EAD.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__tmp_ms_x__3214EC07B1AEAFBA");

                    b.HasIndex(new[] { "Email" }, "UQ__tmp_ms_x__A9D10534D3A90284")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EAD.Models.Bill", b =>
                {
                    b.HasOne("EAD.Models.User", "User")
                        .WithMany("Bills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Bills_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EAD.Models.BillRecheckRequest", b =>
                {
                    b.HasOne("EAD.Models.Bill", "Bill")
                        .WithMany("BillRecheckRequests")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RecheckRequest_Bill");

                    b.HasOne("EAD.Models.User", "User")
                        .WithMany("BillRecheckRequests")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_RecheckRequest_User");

                    b.Navigation("Bill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EAD.Models.DailyConsumption", b =>
                {
                    b.HasOne("EAD.Models.Bill", "Bill")
                        .WithMany("DailyConsumptions")
                        .HasForeignKey("BillId")
                        .HasConstraintName("FK_DailyConsumptions_Bill");

                    b.HasOne("EAD.Models.MealItem", "MealItem")
                        .WithMany("DailyConsumptions")
                        .HasForeignKey("MealItemId")
                        .IsRequired()
                        .HasConstraintName("FK_DailyConsumption_MealItem");

                    b.HasOne("EAD.Models.User", "User")
                        .WithMany("DailyConsumptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DailyConsumption_User");

                    b.Navigation("Bill");

                    b.Navigation("MealItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EAD.Models.DailyMenu", b =>
                {
                    b.HasOne("EAD.Models.MealItem", "MealItem")
                        .WithMany("DailyMenus")
                        .HasForeignKey("MealItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DailyMenu_MealItem");

                    b.Navigation("MealItem");
                });

            modelBuilder.Entity("EAD.Models.Bill", b =>
                {
                    b.Navigation("BillRecheckRequests");

                    b.Navigation("DailyConsumptions");
                });

            modelBuilder.Entity("EAD.Models.MealItem", b =>
                {
                    b.Navigation("DailyConsumptions");

                    b.Navigation("DailyMenus");
                });

            modelBuilder.Entity("EAD.Models.User", b =>
                {
                    b.Navigation("BillRecheckRequests");

                    b.Navigation("Bills");

                    b.Navigation("DailyConsumptions");
                });
#pragma warning restore 612, 618
        }
    }
}
